### ISSUE TITLE
Why not integrate/build on top of scons?

### ISSUE THREAD

**Issue by dant3** [amigocloud/amigomake#1]
Your project looks interesting, however one question stuck in my head - why reinvent the wheel and create a new build system? While you could leverage of existing tools and make your own more robust with their help. Since this project is written in Python... There are scons around, which is happens to define a build in python too, is a fairly known and documented tool, and has some integration with some IDE's. So my question is, why not leverage from scons for example, and not make a scons extension for cross-buildiing oss projects for iOS and Android?

**Comment by schernetsky** [comment]
Mostly just the way it started. We needed something quick mainly to manage/compile oss projects. After that adding regular c/c++ compilation was beneficial for us and required little extra work.

You're right that in the long run it may make sense to integrate with scons, but we just haven't had the need to do that.
